M48
; DRILL file {KiCad 7.0.7} date Sun Jul 14 10:36:35 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-14T10:36:35+05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1252
%
G90
G05
T1
X3.9882Y-1.0728
X4.3031Y-1.0728
T2
X5.1539Y-2.2799
X5.3508Y-2.0831
X5.3508Y-2.4768
X5.4492Y-2.0831
X5.4492Y-2.4768
T3
X2.7165Y-0.9254
X2.7165Y-1.9093
T0
M30
